config/routes.rb
Ostaz2::Application.routes.draw do
  
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
   
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :users
  
  resources :transactions,except: [:destroy]
  resources :accounts,except: [:destroy]
  resources :totals , only: [:index,:create,:new]#except: :destroy
  get ':controller(/:action(/:id))'

  

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  before_filter :authenticate_user!
  load_and_authorize_resource  
  def index
    @transactions = Transaction.accessible_by(current_ability)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new
	@accounts = @account = Account.where("name not like ?","total%").accessible_by(current_ability)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
	@accounts = @account = Account.where("name not like ?","total%").accessible_by(current_ability)
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
	@transaction = Transaction.new
	@acc_from = Account.find_by_id(params[:transaction][:from_id])
	@acc_to = Account.find_by_id(params[:transaction][:to_id])	
    @transaction.amount = params[:transaction][:amount]
	@transaction.description = params[:transaction][:description]
	@transaction.to = @acc_to
	@transaction.from = @acc_from
	@transaction.receipt = params[:transaction][:receipt]
	@error = Transaction.validateTransaction(@transaction) 
	if(@error != "")
		@accounts  = Account.where("name not like ?","total%").accessible_by(current_ability)
		respond_to do |format|
			format.html { render action: "new" }
			format.json { render json: @transaction.errors, status: :unprocessable_entity }
		end
		return
	end
	@result = Transaction.saveAndUpdateMainAccounts(@transaction)
    respond_to do |format|
      if ( @result)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully saved.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
      else
		@accounts  = Account.where("name not like ?","total%").accessible_by(current_ability)
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
	    @accounts = @account = Account.where("name not like ?","total%").accessible_by(current_ability)
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for @transaction,  :html => { :multipart => true }  do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if !@error.nil? && @error != "" %>
    <div id="error_explanation">
      <h2> error prohibited this account from being saved:</h2>
      <ul>      
        <li><%= @error %></li>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount,:min => 10, :readonly => f.object.persisted? %>
  </div>  
  <div class="field">
	<%= f.label :from %><br />
	<%= f.collection_select :from_id, @accounts, :id, :name, {:prompt => "Please select ...."},{ :disabled => f.object.persisted? }%>
  </div>
  <div class="field">
	<%= f.label :to %><br />
	<%= f.collection_select :to_id, @accounts, :id, :name, {:prompt => "Please select ...."},{ :disabled => f.object.persisted? } %>
  </div>
  <div class="field">
    <%= f.label :receipt %><br />
	<% if(f.object.persisted?)%>
		<%=  @transaction.receipt_file_name %>
        <a data-toggle="modal" href="#receipt-<%= @transaction.id%>"  type="button">view</a>
        <%= render 'receipt' %>
    <% end %>
	<%= f.file_field :receipt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/_receipt.html.erb
<div id="receipt-<%= @transaction.id%>" class="modal" style="display: none;background-color: #B2B2B2;">
  <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>View Receipt</h3>
  </div>
  <div class="modal-body">
  <%= image_tag @transaction.receipt.url %>
  </div>
  <div class="modal-footer">      
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Transactions</h1>
<div class="span8">
<table class="table table-condensed">
  <tr>
    <th>ID</th>
    <th>Amount</th>
    <th>From</th>	
    <th>To</th>
	<th>User</th>
	<th>Date</th>
	<th>Receipt</th>
    <th></th>
	<th></th>	
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.id %></td>
    <td><%= transaction.amount %></td>
	<td><%= link_to  transaction.from.name , transaction.from %></td>
	<td><%= link_to  transaction.to.name , transaction.to %></td>
	<td><%= transaction.from.user.name  %></td>
	<td><%= transaction.created_at  %></td>
	<td>
	<% if (transaction.receipt_file_name.nil?) %>
		-
	<% else %>
		<%= transaction.receipt_file_name %>
	<% end %>
	</td>
    <td><%= link_to 'Show', transaction %></td> 
	<% if can? :update, Transaction %>
	<td><%= link_to 'Edit', edit_transaction_path(transaction) %></td> 	
	<% end %>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'New Transaction', new_transaction_path %>
</div>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<table class="table table-condensed">
<th style='width:50%'></th>
<th style='width:50%'></th>
<tr>
	<td><b>Date:</b></td>
	<td><%= @transaction.created_at %></td>
</tr>
<tr>
	<td><b>Description:</b></td>
	<td><%= @transaction.description %></td>
</tr>
<tr>
	<td><b>Amount</b></td>
	<td><%= @transaction.amount %></td>
</tr>
<tr>
	<td><b>From:</b></td>
	<td><%= @transaction.from.name %></td>
</tr>
<tr>
	<td><b>To:</b></td>
	<td><%= @transaction.to.name %></td>
</tr>
<tr>
	<td><b>Receipt:</b></td>
	<td>
	<% if @transaction.receipt_file_name.nil? %>
		-
	<% else %>
		<%=  @transaction.receipt_file_name %>
        <a data-toggle="modal" href="#receipt-<%= @transaction.id%>"  type="button">view</a>
        <%= render 'receipt' %>
	<% end %>
	</td>
</tr>
</table>
<%= link_to 'Back', transactions_path %>