config/routes.rb
Ostaz2::Application.routes.draw do
  
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
   
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :users
  
  resources :transactions,except: [:destroy]
  resources :accounts,except: [:destroy]
  resources :totals , only: [:index,:create,:new]#except: :destroy
  get ':controller(/:action(/:id))'

  

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Twitter Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>      
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
	  <% if user_signed_in? %>
			<li>
				<%= link_to 'Welcome '+ current_user.name ,edit_user_registration_path %>
			</li>
		<% end %>
        <%= render 'layouts/navigation_links' %>
		
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb

  <% if user_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <% if current_user.has_role? :Owner %>
      <li>
      <%= link_to('Users', users_path) %>	  
      </li>
    <% end %>
	<li>
      <%= link_to('Accounts', accounts_path) %>
    </li>
	<li>
      <%= link_to('Transactions', transactions_path) %>
    </li>
	<% if current_user.has_role? :User %>
		<li>
		  test
		</li>
	<% end %>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ostaz</title>
    <meta name="description" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>