config/routes.rb
Ostaz2::Application.routes.draw do
  
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
   
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :users
  
  resources :transactions,except: [:destroy]
  resources :accounts,except: [:destroy]
  resources :totals , only: [:index,:create,:new]#except: :destroy
  get ':controller(/:action(/:id))'

  

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :AccountType
  belongs_to :user ,:class_name => "User"
  attr_accessible :AccountType_id, :balance, :description, :name, :user
  validates_presence_of :AccountType
  
  def self.getTotals
		@accounts = Account.where("name like ?","total%")
  end
  def self.getTotalsArr
	@accounts =[]
		@asst_total = Account.find_by_name('Assets_total')
		unless @asst_total.nil?
			@accounts << @asst_total
		end
		@liab_total = Account.find_by_name('Liabilities_total')
		unless @liab_total.nil?
			@accounts << @liab_total
		end
		@Eq_total = Account.find_by_name('Equity_total')
		unless @Eq_total.nil?
			@accounts << @Eq_total
		end
		@Exp_total = Account.find_by_name('Expenses_total')
		unless @Exp_total.nil?
			@accounts << @Exp_total
		end	
		@accounts
  end
  
  def self.getTotalAssets
	@all_assets = Account.find_all_by_AccountType_id(AccountType.find_by_id(1))
	@total_balance = 0
	@all_assets.each do |acc|
		@total_balance = @total_balance + acc.balance
	end
	@total_balance
  end
  
  def self.totalsHash	
	@totals=Hash.new
	@accounts = Account.where("name like ?","total%")
	
	@accounts.each do |account|		
		@totals[account.name] = account
	end
	@totals	
  end
  def self.createTotals(amount,current_user)	
	#Account.where(Account.arel_table[:name].matches('%total')).destroy_all
	@types = AccountType.all
	@all=[]
	@types.each do |type|
		@account = Account.new
		@account.name = "total_"+type.name
		@account.description = "The sum of all "+type.name+"accounts."
		@account.AccountType = type
		@account.user = User.find_by_id(current_user.id) 
		if(type.name == "Assets" || type.name == "Equity")
			@account.balance = amount
		else
			@account.balance = 0.0
		end
		@account.save		
		@all << @account
	end
	@all
	
  end
  def self.addAndUpdateTotals(acc)
	@totals = Account.totalsHash
	@error=""
	if(acc.AccountType.id == 1 || acc.AccountType.id == 4)
		@total_Assets = @totals['total_Assets'] 
		if((@total_Assets.balance - acc.balance ) <0)
			@error="There is no enough funds for the initial balance, maximum allowed = " +@total_Assets.balance.to_s
		else
			@total_Exp = @totals['total_Expenses']
			@total_Exp.balance = @total_Exp.balance + acc.balance
			@total_Assets.balance = @total_Assets.balance - acc.balance
			if(acc.save)
				@total_Exp.save
				@total_Assets.save
			end
		end
	elsif(acc.AccountType.id == 3)
		@total_eq = @totals['total_Equity']
		@total_eq.balance = @total_eq.balance + acc.balance
		@total_ass = @totals['total_Assets']
		@total_ass.balance = @total_ass.balance + acc.balance
		if(acc.save)
			@total_eq.save
			@total_ass.save
		end
	elsif(acc.AccountType.id == 2)
		@total_liab = @totals['total_Liabilities']
		@total_liab.balance = @total_liab.balance + acc.balance
		@total_Exp = @totals['total_Expenses']
		@total_Exp.balance = @total_Exp.balance + acc.balance
		if(acc.save)
				@total_Exp.save
				@total_liab.save
		end
	else
		@error="Unknown account type"
	end		
	@error	
  end
  def self.creditAssets(amount)
	@assets = Account.find_by_name('total_Assets')
	#@exp = Account.find_by_name('total_Expenses')
	@assets.balance = @assets.balance - amount
	#@exp.balance = @exp.balance + amount
	@assets.save
	#@exp.save
  end
  def self.debitAssets(amount)
	@assets = Account.find_by_name('total_Assets')	
	@assets.balance = @assets.balance + amount	
	@assets.save	
  end
  def self.debitLiabilities(amount)
	@lia = Account.find_by_name('total_Liabilities')	
	@lia.balance = @lia.balance - amount	
	@assets.save	
  end
  def self.creditLiabilities(amount)
	@lia = Account.find_by_name('total_Liabilities')	
	@lia.balance = @lia.balance + amount	
	@lia.save	
  end
  def self.debitExpenses(amount)
	@exp = Account.find_by_name('total_Expenses')	
	@exp.balance = @exp.balance + amount	
	@exp.save	
  end
  def self.creditExpenses(amount)
	@exp = Account.find_by_name('total_Expenses')	
	@exp.balance = @exp.balance - amount	
	@exp.save	
  end
  def self.debitEquity(amount)	
	@exp = Account.find_by_name('total_Expenses')	
	@exp.balance = @exp.balance + amount	
	@exp.save
  end
  def self.creditEquity(amount)
	@exp = Account.find_by_name('total_Expenses')	
	@exp.balance = @exp.balance - amount	
	@exp.save
	
  end
  
end

app/models/account_type.rb
class AccountType < ActiveRecord::Base
  attr_accessible :description, :name, :id
  has_many :Accounts 
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.json
  before_filter :authenticate_user!
  load_and_authorize_resource
  def index
    @accounts = Account.where("name not like ?","total%").accessible_by(current_ability)
	#@account = Account.accessible_by(current_ability)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    params[:user_id] = current_user.id
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new
	@accountTypes = AccountType.find(:all)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
	@accountTypes = AccountType.find(:all)
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])
	@account.user = User.find_by_id(current_user.id)#current_user.id
	@error = Account.addAndUpdateTotals(@account) 	
    respond_to do |format|
      if(@error=="" && @account.errors.empty?) #@account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
		@accountTypes = AccountType.find(:all)
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
		@accountTypes = AccountType.find(:all)
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
	  
      </ul>
    </div>
  <% end %>
   <% if !@error.nil? && @error != "" %>
    <div id="error_explanation">
      <h2> error prohibited this account from being saved:</h2>
      <ul>      
        <li><%= @error %></li>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :balance %><br />
    <%= f.number_field :balance,:min =>0 , :readonly => f.object.persisted? %>
  </div>  
   <div class="field">
	<%= f.label :AccountType_id %><br />
	<%= f.collection_select :AccountType_id, @accountTypes, :id, :name, {:prompt => "Please select ...." }, { :disabled => f.object.persisted? }  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Accounts</h1>
<div class="span8">
<table id="accounts" class="table table-condensed">
  <tr>
    <th>Name</th>   
    <th>Balance</th>
    <th>Accounttype</th>
	<th>user</th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.name %></td>    
    <td><%= account.balance %></td>
    <td><%= account.AccountType.name%></td>
	<td><%= account.user.name%></td>
    <td><%= link_to 'Show', account %></td>
	<% if can? :update, Account %>
	<td><%= link_to 'Edit', edit_account_path(account) %></td> 	
	<% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>|
<%= link_to 'View Main Accounts', totals_path %>
</div>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<table class="table table-condensed">
<th style='width:60%'></th>
<th style='width:40%'></th>
<tr>
	<td><b>Name:</b></td>
	<td><%= @account.name %></td>
</tr>
<tr>
	<td><b>Description:</b></td>
	<td><%= @account.description %></td>
</tr>
<tr>
	<td><b>Balance:</b></td>
	<td> <%= @account.balance %></td>
</tr>
<tr>
	<td> <b>Accounttype:</b></td>
	<td> <%= @account.AccountType.name%></td>
</tr>
</table>
<%= link_to 'Back', accounts_path %>